Allow disabling CRDs for specific controllers
fluxcd-community/helm-charts pull request #144
Opened 2022-11-30 16:16 UTC by julienduchesne

Currently, `installCRDs` is a global flag and there's no way to only install CRDs for certain controllers 
This PR adds another level (true by default for retrocompatibility) that can be used to disable CRD installation for a specific controller

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist

- [ ] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] helm-docs are updated
- [ ] Helm chart is tested
- [ ] Update artifacthub.io/changes in Chart.yaml
- [ ] Run `make reviewable`

2022-12-05 12:29 UTC, dwerder requested changes
We have the following bash file, which is used to generate the CRD files from flux2 upstream. That one needs to be adjusted to generate the the lines correctly, which you added manually.

https://github.com/fluxcd-community/helm-charts/blob/main/hack/generate.sh

2022-12-05 15:26 UTC, stefanprodan commented
@julienduchesne what is the use-case for this? Why would you install a controller without its CRDs, it will just crash loop.

2022-12-05 15:27 UTC, julienduchesne commented
> @julienduchesne what is the use-case for this? Why would you install a controller without its CRDs, it will just crash loop.

I want to use it in combination with `create=false`

2022-12-05 15:29 UTC, stefanprodan commented
> I want to use it in combination with create=false

So then we don't need to add a new flag for this, each CRD should check `controller.create`

2022-12-05 15:32 UTC, julienduchesne commented
> > I want to use it in combination with create=false
> 
> So then we don't need to add a new flag for this, each CRD should check `controller.create`

The new flag is meant to maintain retro-compatibility. If this is now controlled by the `create` flag, then CRDs will disappear unexpectedly for a minor bump 🤔

2022-12-05 16:13 UTC, stefanprodan commented
>  If this is now controlled by the create flag, then CRDs will disappear unexpectedly for a minor bump

I don't think this should affect anyone, if there is no controller to act on the CRs then no harm in removing the CRDs.

2022-12-05 16:37 UTC, julienduchesne commented
> > If this is now controlled by the create flag, then CRDs will disappear unexpectedly for a minor bump
> 
> I don't think this should affect anyone, if there is no controller to act on the CRs then no harm in removing the CRDs.

Makes sense! Done!

2022-12-06 08:53 UTC, dwerder approved these changes

2022-12-06 09:00 UTC, stefanprodan approved these changes
LGTM

Thanks @julienduchesne for making the chart behave more like Flux CLI.

2022-12-06 09:10 UTC, merged

2023-03-15 08:49 UTC, clux commented
> I don't think this should affect anyone, if there is no controller to act on the CRs then no harm in removing the CRDs.

Having just been bitten by this (it affects people who use the chart to only install the CRDs). It would be great to tag changes like this as changes, even if the chance of them actually occurring seems small.