Provide ability to specify kustomize controller envFrom values
fluxcd-community/helm-charts pull request #36
Opened 2021-12-08 18:24 UTC by MxNxPx

#### What this PR does / why we need it:
* Allow for the ability to specify envFrom values for the kustomize controller
* Required namely when using an Azure service principal to decrypt sops encrypted secrets

#### Which issue this PR fixes
https://github.com/fluxcd-community/helm-charts/issues/35

#### Special notes for your reviewer:
Bumped up the chart version to 0.6.5.  Testing performed included a helm template with no errors and a deployment using the envFrom secret helm value.

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested

2021-12-08 21:53 UTC, haarchri commented
for clean commit history please rebase master/main instead merge master/main and please squash you commits

2021-12-09 09:53 UTC, dwerder requested changes

2021-12-09 09:53 UTC, dwerder commented on charts/flux2/templates/kustomize-controller.yaml
> +        {{- if .Values.kustomizecontroller.envFrom.enabled }}
That can be replaced by:
{{- if or (.Values.kustomizecontroller.envFrom.map.name) (.Values.kustomizecontroller.envFrom.secret.name) }}

2021-12-09 09:53 UTC, dwerder commented on charts/flux2/templates/kustomize-controller.yaml
> +          {{- if .Values.kustomizecontroller.envFrom.map.enabled }}
Should be replaced by:
{{- if .Values.kustomizecontroller.envFrom.map.name }}

2021-12-09 09:53 UTC, dwerder commented on charts/flux2/templates/kustomize-controller.yaml
> +          {{- if .Values.kustomizecontroller.envFrom.secret.enabled }}
Should be replaced by:
{{- if .Values.kustomizecontroller.envFrom.secret.name }}

2021-12-09 09:53 UTC, dwerder commented on charts/flux2/values.yaml
> +  # Allows you to load environment variables from kubernetes secret or config map
If you use
   `# --  some text`
It will be shown in the README as value description

2021-12-09 09:53 UTC, dwerder commented on charts/flux2/Chart.yaml
> +version: "0.6.5"
You need to rebase squash and bump version again.

You can do that like this:
```
git reset --soft HEAD~12      <- Number of commits you want to squash
git commit -sm "add envForm for kustomize-controller"
git push --set-upstream origin kustomize-envFrom --force
```

2021-12-09 10:10 UTC, MxNxPx commented
@dwerder - would you mind opening a new pull request if I close this one out?

2021-12-09 10:54 UTC, dwerder commented
@MxNxPx We can do that.

2021-12-09 10:57 UTC, MxNxPx commented
closing this PR so it can be redone more cleanly.
thanks @dwerder !

2021-12-09 10:57 UTC, closed without merging

2021-12-09 10:58 UTC, MxNxPx commented
> @MxNxPx We can do that.

closed this PR if you wouldn't mind opening a new one @dwerder.